from pathlib import Path
ms = "my-paper"
cache = "../cache"

rule all:
    input:
        f"build/{ms}.pdf",
        "supplement/supplement.pdf",
        f"arxiv/build/{ms}.pdf"

rule pdf:
    input:
        f"{ms}.tex",
        "main.tex",
        "math-traditional.tex",
        "ref.bib",
        "code/out/t-fig.pdf",
        "code/out/t-tab.tex"
    output:
        f"build/{ms}.pdf"
    shell:
        f"""
        latexmk --xelatex -output-directory=build -silent {ms}.tex
	texfot xelatex -interaction=nonstopmode -output-directory=build -synctex=1 {ms}.tex
        """

rule supplement:
    input:
        "supplement.tex",
        "math-traditional.tex",
        "ref.bib"
    output:
        f"supplement/supplement.pdf"
    shell:
        f"""
        latexmk --xelatex -output-directory=supplement -silent supplement.tex
	texfot xelatex -interaction=nonstopmode -output-directory=supplement -synctex=1 supplement.tex
        """

rule arxiv:
    input:
        f"build/{ms}.pdf",
        "code/singletex.r"
    output:
        f"arxiv/build/{ms}.pdf"
    shell:
        f"""
        mkdir -p arxiv/build
        Rscript code/singletex.r {ms}.tex arxiv/{ms}.tex
        cd arxiv
        latexmk --xelatex -output-directory=build -silent {ms}.tex
        texfot xelatex -interaction=nonstopmode -output-directory=build -synctex=1 {ms}.tex
        """

rule t_fig:
    input:
        f"{cache}/ex-100-2.csv",
        "code/t-fig.r"
    output:
        "code/out/t-fig.pdf"
    shell:
        """
        cd code
        Rscript t-fig.r
        """

rule t_tab:
    input:
        f"{cache}/ex-100-2.csv",
        "code/t-tab.r"
    output:
        "code/out/t-tab.tex"
    shell:
        """
        cd code
        Rscript t-tab.r
        """

rule math:
    output:
        "math-traditional.tex"
    shell:
        "curl -O https://raw.githubusercontent.com/pbreheny/pb-latex/main/tex/math-traditional.tex"
