from pathlib import Path
ms = "my-paper"
cache = "../cache"

rule all:
    input:
        f"{ms}/{ms}.pdf",
        "supplement/supplement.pdf",
        f"arxiv/build/{ms}.pdf"

rule pdf:
    input:
        f"{ms}.tex",
        "main.tex",
        "math-traditional.tex",
        "ref.bib",
        "results/power.pdf",
        "results/error-rate.tex",
        "smallcap.bst"
    output:
        f"{ms}/{ms}.pdf"
    shell:
        f"latexmk --xelatex -interaction=nonstopmode -output-directory={ms} {ms}.tex"

rule supplement:
    input:
        "supplement.tex",
        "math-traditional.tex",
        "ref.bib",
        "smallcap.bst"
    output:
        "supplement/supplement.pdf"
    shell:
        "latexmk --xelatex -interaction=nonstopmode -output-directory=supplement supplement.tex"

rule arxiv:
    input:
        f"{ms}/{ms}.pdf",
        "code/singletex.r",
        "math-traditional.tex"
    output:
        f"arxiv/build/{ms}.pdf"
    shell:
        f"""
        mkdir -p arxiv/build
        Rscript code/singletex.r {ms}.tex arxiv/{ms}.tex
        cd arxiv
        latexmk --xelatex -interaction=nonstopmode -output-directory=build {ms}.tex
        """

rule power:
    input:
        f"{cache}/ex-100-2.csv",
        "code/power.r"
    output:
        "results/power.pdf"
    shell:
        """
        cd code
        Rscript power.r
        """

rule error_rate:
    input:
        f"{cache}/ex-100-2.csv",
        "code/error-rate.r"
    output:
        "results/error-rate.tex"
    shell:
        """
        cd code
        Rscript error-rate.r
        """
