rule all:
    input: "style-guide.tex"
    output: "../style-guide.pdf"
    shell:
        """
        latexmk --xelatex -output-directory=build style-guide.tex
        cp build/style-guide.pdf ..
        """
